Add simple styles to example website
twigyard/example-site-multi-language pull request #5
Opened 2016-11-07 14:08 UTC by crishpeen

2016-11-09 15:30 UTC, mbohal commented
Please do resolve the conflicts.

2016-11-09 16:33 UTC, adamkudrna requested changes

2016-11-09 16:33 UTC, adamkudrna commented on src/languages/cs_CZ.yml
> +Contact: Kontakt
No newline at end of file

2016-11-09 16:33 UTC, adamkudrna commented on web/css/main.css
> +}
No newline at end of file

2016-11-09 16:33 UTC, adamkudrna commented on src/templates/_layouts/base.html.twig
> +                        <li{% if locale == 'cs_CZ' %} class="active"{% endif %}><a href ="{{ path(page, {}, 'cs_CZ') }}">Cs</a></li>
Please capitalize language codes (CS, EN) or use full language names (Czech, English).

2016-11-09 16:33 UTC, adamkudrna commented on src/templates/cs_CZ/product.html.twig
> +        <li{% if locale == 'cs_CZ' %} class="active"{% endif %}><a href ="{{ path(page, { 'product_slug': prod.cs.slug }, 'cs_CZ') }}">Cs</a></li>
Here goes the same with the languages.

2016-11-09 16:33 UTC, adamkudrna commented on src/templates/en_US/product.html.twig
> +        <li{% if locale == 'cs_CZ' %} class="active"{% endif %}><a href ="{{ path(page, { 'product_slug': prod.cs.slug }, 'cs_CZ') }}">Cs</a></li>
Here goes the same with the languages.

2016-11-10 12:34 UTC, mbohal approved these changes

2016-11-11 14:43 UTC, adamkudrna approved these changes

2016-11-11 14:44 UTC, merged